# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DataTalks',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/DataTalks',
                'lib_path': 'DataTalks'},
  'syms': {'DataTalks.core': {'DataTalks.core.foo': ('core.html#foo', 'DataTalks/core.py')}}}
