project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

resources:
  - metro_areena_homepage_screenshot.png
  - metro_areena_event_calendar_screenshot.png
  - metro_areena_logo.png

metadata-files: [nbdev.yml, sidebar.yml]